pipeline{
agent {
  label "master"
}
tools {
  gradle "gradle-6.5.1"
}
environment {
  VERSION = "jellybean"
}
stages {
stage("Checkout") {
  steps {
            // One or more steps need to be included within the steps block.
            checkout ([$class: "GitSCM",
                branches: [[name: "master"]],
                extensions: [[$class: "WipeWorkspace"]],
                userRemoteConfigs: [[url: "https://github.com/yemisie/devops-webapp.git"]]
            ])
  }
}
stage("Details") {
  steps {
            // One or more steps need to be included within the steps block.
            echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
            echo "{env.VERSION}"
  }

  when {
    environment name: "VERSION", value: "jellybean"
  }
}
stage("Build") {
  steps {
            // One or more steps need to be included within the steps block.
            sh "gradle build"
  }
}
}
}